### ISSUE TITLE
[Proposal] Tool should be extended to allow checking latest commit.

### ISSUE THREAD

**Issue by samiwel** [ONSdigital/git-diff-check#14]
Following discussion at the latest IA/TechLead meeting, I am in the process of writing the Docker configuration for containerising this utility.

As I understand it, the tool currently expects to be run as part of a pre-commit git hook. As such, it does an explicit check to see if there are any staged changes and executes a bunch of rules against the diff patch.

Whilst the existing use case is valid and useful, if we were to run this tool in a container as part of a Concourse pipeline, I think having the ability to run the tool against the latest commit. e.g.

```
git diff -U0 HEAD^1..HEAD
``` 

would also be helpful. Jobs in the eQ concourse pipeline are triggered off new commits and so it would be useful to attach any repo as a resource to the containerised `git-diff-check` tool and have it perform a check on the latest commit of that repo.

**Comment by samiwel** [comment]
@necrophonic What do think?

**Comment by necrophonic** [comment]
The best thing to do would probably be add a new wrapper that sources the latest commit (using `git diff -U0 HEAD^1..HEAD` or similar as you said) and feeds it to the checker engine.

The current command line tool is just an example veneer over the checking engine (that just expects a diff) and is designed in that way to be extensible rather than being tied into a single workflow (e.g. a git hook) - see the service implementation in https://github.com/ONSdigital/git-diff-check-service/tree/alpha

**Comment by necrophonic** [comment]
For reference, the api is available godoc'd at https://godoc.org/github.com/ONSdigital/git-diff-check/diffcheck

**Comment by necrophonic** [comment]
Closing for now
